all:
  vars:
    ansible_user: vineethvijay
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  children:
    # ---------- Proxmox hypervisors ----------
    proxmox:
      children:
        proxmox_local:
          hosts:
            pve-local:
              ansible_host: 192.168.1.11
              ansible_user: root
        proxmox_remote:
          hosts:
            pve-remote:
              ansible_host: 192.168.1.8
              ansible_user: root

    # ---------- Kubernetes nodes ----------
    k8s:
      children:
        control_plane:
          children:
            control_plane_init:
              hosts:
                k8s-cp:
                  ansible_host: 192.168.1.200
                  vmid: 200
                  pve_host: pve-local
            control_plane_join:
              hosts:
                k8s-cp2:
                  ansible_host: 192.168.1.205
                  vmid: 205
                  pve_host: pve-remote
                k8s-cp3:
                  ansible_host: 192.168.1.206
                  vmid: 206
                  pve_host: pve-local

        workers:
          children:
            workers_local:
              hosts:
                k8s-w1:
                  ansible_host: 192.168.1.201
                  vmid: 201
                  pve_host: pve-local
                k8s-w2:
                  ansible_host: 192.168.1.202
                  vmid: 202
                  pve_host: pve-local
                k8s-w3:
                  ansible_host: 192.168.1.203
                  vmid: 203
                  pve_host: pve-local
            workers_remote:
              hosts:
                k8s-w4:
                  ansible_host: 192.168.1.204
                  vmid: 204
                  pve_host: pve-remote

    # Workers that need NFS mounts
    nfs_workers:
      hosts:
        k8s-w1:
        k8s-w2:
        k8s-w4:
