replicaCount: 1

image:
  repository: filebrowser/filebrowser
  tag: latest

timezone: "Europe/London"
existingClaim: filebrowser-config-nfs

ingress:
  enabled: true
  host: filebrowser.homelab.local
  homepage:
    name: File Browser
    description: Browse NFS Disk Files
    icon: filebrowser
    group: Infrastructure

resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 256Mi

nfs:
  hddInt: /mnt/nfs/hdd-int
  nasMedia: /mnt/nfs/nas-media
  nasBackups: /mnt/nfs/nas-backups
