---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: glances
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    app: glances
spec:
  selector:
    matchLabels:
      app: glances
  template:
    metadata:
      labels:
        app: glances
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 192.168.1.242
          - 8.8.8.8
        searches:
          - k8s.local
          - home
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: glances
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 61208
              hostPort: 61208
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
          env:
            - name: GLANCES_OPT
              value: "-w --enable-plugin sensors --enable-plugin gpu"
          volumeMounts:
            - name: host-os-release
              mountPath: /etc/os-release
              readOnly: true
            - name: host-hostname
              mountPath: /etc/hostname
              readOnly: true
            - name: host-sys
              mountPath: /sys
              readOnly: true
            - name: host-dev-nvidia
              mountPath: /dev/nvidia0
            - name: host-dev-nvidiactl
              mountPath: /dev/nvidiactl
      volumes:
        - name: host-os-release
          hostPath:
            path: /etc/os-release
            type: File
        - name: host-hostname
          hostPath:
            path: /etc/hostname
            type: File
        - name: host-sys
          hostPath:
            path: /sys
            type: Directory
        - name: host-dev-nvidia
          hostPath:
            path: /dev/nvidia0
            type: ""
        - name: host-dev-nvidiactl
          hostPath:
            path: /dev/nvidiactl
            type: ""
      restartPolicy: Always
